version: "3.3"

services:
  elastic:
    container_name: elastic
    build:
      context: .
      dockerfile: ./dockerfiles/elastic
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./dockerfiles/webapp
    volumes:
      - ./webapp/:/usr/src/app
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 80:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/web_dev # new
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web_test # new
    depends_on: # new
      - db
      - elastic

  db:
    build:
      context: .
      dockerfile: ./dockerfiles/postgres
    container_name: postgres
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
